import { NextRequest } from "next/server";
import { getAuthenticatedUser } from "@/lib/auth";
import { ok, fail } from "@/lib/api-response";
import { inviteMemberSchema } from "@/lib/validations/teams";
import { createClient } from "@/lib/supabase/server";
import { APP_NAME } from "@/lib/config";

export async function POST(req: NextRequest) {
  try {
    // 1. AUTH
    const auth = await getAuthenticatedUser();
    if (!auth) return fail("unauthorized", "Sign in to continue.", 401);

    // 2. VALIDATE
    const body: unknown = await req.json();
    const parsed = inviteMemberSchema.safeParse(body);
    if (!parsed.success) return fail("invalid_input", parsed.error.issues[0]?.message ?? "Invalid input.", 422);

    const { email } = parsed.data;

    // 3. AUTHORIZE — caller must own an active team plan subscription
    const supabase = await createClient();
    const { data: sub } = await supabase
      .from("subscriptions")
      .select("id, max_seats, plan_id, team_id")
      .eq("owner_id", auth.user.id)
      .eq("status", "active")
      .maybeSingle();

    if (!sub) return fail("forbidden", "You don't have an active subscription.", 403);
    if (!sub.team_id) return fail("forbidden", "Your plan does not include team features.", 403);
    if (sub.max_seats <= 1) return fail("forbidden", "Your plan does not include team seats.", 403);

    // Check current seat count (accepted members only)
    const { count: memberCount } = await supabase
      .from("team_members")
      .select("*", { count: "exact", head: true })
      .eq("subscription_id", sub.id)
      .eq("invite_accepted", true);

    if ((memberCount ?? 0) >= sub.max_seats) {
      return fail("conflict", `Your team is at the ${sub.max_seats}-seat limit.`, 409);
    }

    // 4. EXECUTE — insert invite (token generated by DB default)
    const { data: invite, error: inviteError } = await supabase
      .from("team_invites")
      .insert({
        team_id:    sub.team_id,
        email,
        invited_by: auth.user.id,
      })
      .select("id, token")
      .single();

    if (inviteError) {
      console.error("[teams/invite] insert error:", inviteError);
      return fail("internal_error", "Could not create invite. Please try again.", 500);
    }

    // 5. Send invite email via Resend
    const appUrl = process.env.NEXT_PUBLIC_APP_URL ?? "http://localhost:3000";
    const acceptUrl = `${appUrl}/teams/accept?token=${invite.token}`;
    await sendInviteEmail({ email, invitedBy: auth.user.email, acceptUrl });

    return ok({ token: invite.token }, 201);
  } catch (err) {
    console.error("[teams/invite] unexpected error:", err);
    return fail("internal_error", "Something went wrong.", 500);
  }
}

async function sendInviteEmail(opts: {
  email: string;
  invitedBy: string;
  acceptUrl: string;
}): Promise<void> {
  const apiKey = process.env.RESEND_API_KEY;
  if (!apiKey) {
    console.warn("[teams/invite] RESEND_API_KEY not set — email not sent. Accept URL:", opts.acceptUrl);
    return;
  }

  try {
    await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${apiKey}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        from: `${APP_NAME} <noreply@joincreatly.com>`,
        to: opts.email,
        subject: `${opts.invitedBy} invited you to join their ${APP_NAME} team`,
        html: `
          <p>You've been invited to join a team on ${APP_NAME}.</p>
          <p><a href="${opts.acceptUrl}" style="background:#1a3d2f;color:#fff;padding:12px 24px;border-radius:8px;text-decoration:none;display:inline-block;">Accept invite</a></p>
          <p style="color:#888;font-size:12px;">This invite expires in 7 days. If you didn't expect this email, you can safely ignore it.</p>
        `,
      }),
    });
  } catch (err) {
    // Don't fail the API response if email delivery fails — log and continue.
    console.error("[teams/invite] email send error:", err);
  }
}
